"""Core enums shared by deterministic TraceGuard domain logic."""

from enum import StrEnum


class ProviderMode(StrEnum):
    SCRIPTED = "SCRIPTED"
    LIVE = "LIVE"


class DiagnosticToolName(StrEnum):
    GET_RUN_OVERVIEW = "get_run_overview"
    GET_RUN_EVENTS = "get_run_events"
    GET_STAGE_ARTIFACT = "get_stage_artifact"
    SEARCH_RUNBOOK = "search_runbook"


class WorkflowState(StrEnum):
    CREATED = "CREATED"
    EXTRACTING = "EXTRACTING"
    STRUCTURE_VALIDATING = "STRUCTURE_VALIDATING"
    DOMAIN_VALIDATING = "DOMAIN_VALIDATING"
    BUSINESS_VALIDATING = "BUSINESS_VALIDATING"
    ERP_CALLING = "ERP_CALLING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class InvestigationState(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class RecoveryState(StrEnum):
    NONE = "NONE"
    ALLOW = "ALLOW"
    BLOCK = "BLOCK"
    REQUIRE_REVIEW = "REQUIRE_REVIEW"
    RETRYING = "RETRYING"
    RECOVERED = "RECOVERED"
    RETRY_EXHAUSTED = "RETRY_EXHAUSTED"


class FailureCategory(StrEnum):
    EXTRACTION_FAILURE = "EXTRACTION_FAILURE"
    STRUCTURAL_VALIDATION_FAILURE = "STRUCTURAL_VALIDATION_FAILURE"
    DOMAIN_VALIDATION_FAILURE = "DOMAIN_VALIDATION_FAILURE"
    BUSINESS_RULE_VIOLATION = "BUSINESS_RULE_VIOLATION"
    EXTERNAL_TRANSIENT_FAILURE = "EXTERNAL_TRANSIENT_FAILURE"
    EXTERNAL_PERMANENT_FAILURE = "EXTERNAL_PERMANENT_FAILURE"
    INVESTIGATION_FAILURE = "INVESTIGATION_FAILURE"
    RECOVERY_FAILURE = "RECOVERY_FAILURE"


class CanonicalErrorCode(StrEnum):
    EXTRACTION_MODEL_ERROR = "EXTRACTION_MODEL_ERROR"
    ORDER_STRUCTURE_INVALID = "ORDER_STRUCTURE_INVALID"
    CUSTOMER_NUMBER_MISSING = "CUSTOMER_NUMBER_MISSING"
    PRODUCT_CODE_MISSING = "PRODUCT_CODE_MISSING"
    QUANTITY_MISSING = "QUANTITY_MISSING"
    QUANTITY_NON_POSITIVE = "QUANTITY_NON_POSITIVE"
    ERP_UNAVAILABLE = "ERP_UNAVAILABLE"
    ERP_REJECTED = "ERP_REJECTED"
    INVESTIGATION_INVALID_OUTPUT = "INVESTIGATION_INVALID_OUTPUT"
    ERP_RETRY_EXHAUSTED = "ERP_RETRY_EXHAUSTED"


class RecoveryAction(StrEnum):
    NO_ACTION = "NO_ACTION"
    RETRY_SAME_INPUT = "RETRY_SAME_INPUT"
    REQUEST_INPUT_CORRECTION = "REQUEST_INPUT_CORRECTION"
    REQUEST_HUMAN_REVIEW = "REQUEST_HUMAN_REVIEW"


class PolicyDecisionType(StrEnum):
    ALLOW = "ALLOW"
    BLOCK = "BLOCK"
    REQUIRE_REVIEW = "REQUIRE_REVIEW"


class PolicyReason(StrEnum):
    ELIGIBLE_TRANSIENT_RETRY = "ELIGIBLE_TRANSIENT_RETRY"
    HUMAN_INPUT_REQUIRED = "HUMAN_INPUT_REQUIRED"
    NON_RETRYABLE_BUSINESS_RULE = "NON_RETRYABLE_BUSINESS_RULE"
    WORKFLOW_NOT_FAILED = "WORKFLOW_NOT_FAILED"
    INVALID_INVESTIGATION = "INVALID_INVESTIGATION"
    DIAGNOSIS_CONFLICT = "DIAGNOSIS_CONFLICT"
    ACTION_CONFLICT = "ACTION_CONFLICT"
    IDEMPOTENCY_KEY_MISSING = "IDEMPOTENCY_KEY_MISSING"
    RETRY_LIMIT_REACHED = "RETRY_LIMIT_REACHED"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"


class Confidence(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class EvidenceSource(StrEnum):
    RUN_EVENT = "RUN_EVENT"
    EXTRACTION = "EXTRACTION"
    VALIDATION = "VALIDATION"
    EXTERNAL_CALL = "EXTERNAL_CALL"
    RUNBOOK = "RUNBOOK"


class EvidenceRole(StrEnum):
    TERMINAL_CAUSE = "TERMINAL_CAUSE"
    SUPPORTING = "SUPPORTING"
    NON_CAUSAL_CONTEXT = "NON_CAUSAL_CONTEXT"


class InvestigationFailureReason(StrEnum):
    UNKNOWN_TOOL = "UNKNOWN_TOOL"
    INVALID_TOOL_ARGUMENTS = "INVALID_TOOL_ARGUMENTS"
    CROSS_RUN_ACCESS = "CROSS_RUN_ACCESS"
    TOOL_EXECUTION_FAILED = "TOOL_EXECUTION_FAILED"
    TOOL_CALL_LIMIT = "TOOL_CALL_LIMIT"
    MODEL_TURN_LIMIT = "MODEL_TURN_LIMIT"
    MODEL_REFUSAL = "MODEL_REFUSAL"
    MODEL_TIMEOUT = "MODEL_TIMEOUT"
    MODEL_FAILURE = "MODEL_FAILURE"
    MALFORMED_REPORT = "MALFORMED_REPORT"
    REPORT_NOT_GROUNDED = "REPORT_NOT_GROUNDED"


class EventOutcome(StrEnum):
    CONTINUED = "CONTINUED"
    RECOVERED = "RECOVERED"
    TERMINAL = "TERMINAL"
    SUCCESS = "SUCCESS"


CANONICAL_FAILURE_CATEGORY: dict[CanonicalErrorCode, FailureCategory] = {
    CanonicalErrorCode.EXTRACTION_MODEL_ERROR: FailureCategory.EXTRACTION_FAILURE,
    CanonicalErrorCode.ORDER_STRUCTURE_INVALID: FailureCategory.STRUCTURAL_VALIDATION_FAILURE,
    CanonicalErrorCode.CUSTOMER_NUMBER_MISSING: FailureCategory.DOMAIN_VALIDATION_FAILURE,
    CanonicalErrorCode.PRODUCT_CODE_MISSING: FailureCategory.DOMAIN_VALIDATION_FAILURE,
    CanonicalErrorCode.QUANTITY_MISSING: FailureCategory.DOMAIN_VALIDATION_FAILURE,
    CanonicalErrorCode.QUANTITY_NON_POSITIVE: FailureCategory.BUSINESS_RULE_VIOLATION,
    CanonicalErrorCode.ERP_UNAVAILABLE: FailureCategory.EXTERNAL_TRANSIENT_FAILURE,
    CanonicalErrorCode.ERP_REJECTED: FailureCategory.EXTERNAL_PERMANENT_FAILURE,
    CanonicalErrorCode.INVESTIGATION_INVALID_OUTPUT: FailureCategory.INVESTIGATION_FAILURE,
    CanonicalErrorCode.ERP_RETRY_EXHAUSTED: FailureCategory.RECOVERY_FAILURE,
}
